openapi: 3.0.3
info:
  title: EV3-REST
  description: EV3-REST
  version: 0.1.0
servers:
  - url: 'http://127.0.0.1:8080/api/v1'

tags:
  - name: power
  - name: motor
  - name: sensor
  - name: sound
paths:
  '/power':
    get:
      tags:
        - power
      responses:
        '200':
          description: 'Get general system info'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PowerInfo'

  '/motor/stopall':
    post:
      tags:
        - motor
      description: 'Stops all connected motors'
      responses:
        '200':
          description: 'Success'
        '400':
          description: 'Client error'
        '500':
          description: 'Server error'

  '/sound/tone':
    post:
      tags:
        - sound
      requestBody:
        description: 'Tone to be played'
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Tone'
      responses:
        '200':
          description: 'Tone successfully played'
        '400':
          description: 'Client error'
        '500':
          description: 'Server error'

  '/sound/tones':
    post:
      tags:
        - sound
      requestBody:
        description: 'Array of tones to be played'
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/Tone'
      responses:
        '200':
          description: 'Tone successfully played'
        '400':
          description: 'Client error'
        '500':
          description: 'Server error'

components:
  schemas:
    Tone:
      type: object
      properties:
        frequency:
          type: integer
        length_ms:
          type: integer

    PowerInfo:
      type: object
      properties:
        voltage:
          type: number
          description: Voltage returns voltage measured from the power supply in volts.
        current:
          type: number
          description: Current returns the current drawn from the power supply in milliamps.
        voltage_max:
          type: number
          description: VoltageMax returns the maximum design voltage for the power supply in volts.
        voltage_min:
          type: number
          description: VoltageMin returns the minimum design voltage for the power supply in volts.
        technology:
          type: string
          description: Technology returns the battery technology of the power supply.
        type:
          type: string
          description: Type returns the battery type of the power supply.
        u_event:
          type: object
          description: Uevent returns the current uevent state for the power supply.
          additionalProperties:
            type: string

