# coding: utf-8

"""
    EV3-REST

    EV3-REST  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""

import unittest

import ev3api
from ev3api.model.tacho_motor import TachoMotor
from ev3api import configuration


class TestTachoMotor(unittest.TestCase):
    """TachoMotor unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
