# coding: utf-8

"""
    EV3-REST

    EV3-REST  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""

from ev3api.paths.button_pressed.get import ButtonPressedGet
from ev3api.paths.led_flash.post import LedFlashPost


class LedApi(
    ButtonPressedGet,
    LedFlashPost,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
