# coding: utf-8

"""
    EV3-REST

    EV3-REST  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""

from ev3api.paths.motor_steer_counts.post import MotorSteerCountsPost
from ev3api.paths.motor_steer_duration.post import MotorSteerDurationPost
from ev3api.paths.motor_steer_reset.post import MotorSteerResetPost
from ev3api.paths.motor_stop_all.post import MotorStopAllPost
from ev3api.paths.motor_tacho.get import MotorTachoGet
from ev3api.paths.motor_tacho.post import MotorTachoPost
from ev3api.paths.motor_tacho_type_port.get import MotorTachoTypePortGet


class MotorApi(
    MotorSteerCountsPost,
    MotorSteerDurationPost,
    MotorSteerResetPost,
    MotorStopAllPost,
    MotorTachoGet,
    MotorTachoPost,
    MotorTachoTypePortGet,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
