# coding: utf-8

"""
    EV3-REST

    EV3-REST  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""

from ev3api.paths.sensor.get import SensorGet
from ev3api.paths.sensor_type.get import SensorTypeGet
from ev3api.paths.sensor_type.put import SensorTypePut
from ev3api.paths.sensor_type_text_values.get import SensorTypeTextValuesGet
from ev3api.paths.sensor_type_values.get import SensorTypeValuesGet


class SensorApi(
    SensorGet,
    SensorTypeGet,
    SensorTypePut,
    SensorTypeTextValuesGet,
    SensorTypeValuesGet,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
