# coding: utf-8

"""
    EV3-REST

    EV3-REST  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""

from ev3api.paths.sound_beep.post import SoundBeepPost
from ev3api.paths.sound_speak.post import SoundSpeakPost
from ev3api.paths.sound_tone.post import SoundTonePost
from ev3api.paths.sound_tones.post import SoundTonesPost


class SoundApi(
    SoundBeepPost,
    SoundSpeakPost,
    SoundTonePost,
    SoundTonesPost,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
