name: Build and release

on:
  push:
  release:
    types:
      - created

jobs:
  build-go-server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.18

      - name: Generate go server
        uses: docker://openapitools/openapi-generator-cli:v6.6.0
        with:
          args: generate -i openapi/spec.yaml -g go-server -o tmp -c openapi/server-config.yml

      - name: Copy generated server code
        run: |
          mkdir -p internal/gen
          cp -r tmp/openapi internal/gen/.
          cp -r tmp/api internal/gen/.

      - name: Install dependencies
        run: |
          go get EV3-API
          go install golang.org/x/tools/cmd/goimports@latest

      - name: Lint with goimports
        run: |
          goimports -l -w internal/gen/openapi
          gofmt -l -w internal/gen/openapi

      - name: Build package
        run: |
          go build -v -o ev3api-server -ldflags="-s -w" EV3-API/cmd
        env:
          GOOS: linux
          GOARCH: arm
          GOARM: 5

      - name: Test
        run: |
          go test EV3-API/cmd -json > TestResults.json

      - name: Upload Go test results
        uses: actions/upload-artifact@v3
        with:
          name: Go-results
          path: TestResults.json

      - name: Upload Go binary
        uses: actions/upload-artifact@v3
        with:
          name: Go-binary
          path: ev3api-server
          retention-days: 7


  build-java-client:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Generate java client
        uses: docker://openapitools/openapi-generator-cli:v6.6.0
        with:
          args: generate -i openapi/spec.yaml -o clients/java-tmp -g java -c openapi/java-client-config.yaml

      - name: Copy generated java code
        run: |
          mkdir -p clients/ev3-java/ev3api
          cp -r clients/java-tmp/* clients/ev3-java/ev3api/.

      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
        
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Run build with Gradle Wrapper
        run: ./gradlew shadowJar
        working-directory: ./clients/ev3-java

      - name: Upload Java fat jar
        uses: actions/upload-artifact@v3
        with:
          name: Java-Jar
          path: clients/ev3-java/build/libs/ev3-java-${{ github.ref_name }}-all.jar
          retention-days: 7


  build-python-client:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Generate java client
        uses: docker://openapitools/openapi-generator-cli:v6.6.0
        with:
          args: generate -i openapi/spec.yaml -o clients/python-tmp -g python -c openapi/python-client-config.yaml

      - name: Copy generated python code
        run: |
          cp -r clients/python-tmp/* clients/ev3-python/.

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build
        working-directory: ./clients/ev3-python

      - name: Build package
        run: python -m build
        working-directory: ./clients/ev3-python

      - name: Upload Python wheel
        uses: actions/upload-artifact@v3
        with:
          name: Python-Wheel
          path: clients/ev3-python/dist/ev3api-*-py3-none-any.whl
          retention-days: 7


  upload-release-assets:
    runs-on: ubuntu-latest
    needs: [build-go-server, build-java-client, build-python-client]
    if: github.event_name == 'release' # && github.event.action == 'created'
    steps:
      - name: Download go server
        uses: actions/download-artifact@v3
        with:
          name: Go-binary

      - name: Download java client
        uses: actions/download-artifact@v3
        with:
          name: Java-Jar

      - name: Download python client
        uses: actions/download-artifact@v3
        with:
          name: Python-Wheel

      - name: Upload Go server Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./ev3api-server
          asset_name: ev3api-server
          asset_content_type: application/octet-stream

      - name: Upload Java Client Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./ev3-java-${{ github.ref_name }}-all.jar
          asset_name: ev3-java-${{ github.ref_name }}-all.jar
          asset_content_type: application/java-archive

      - name: Upload Python Client Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./ev3api-${{ github.ref_name }}-py3-none-any.whl
          asset_name: ev3api-${{ github.ref_name }}-py3-none-any.whl
          asset_content_type: application/zip
