name: Go binary

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Gerate go server
        uses: docker://openapitools/openapi-generator-cli
        with:
          args: generate -i openapi/spec.yaml -g go-server -o tmp -c openapi/server-config.yml

      - name: Copy generated server code
        run: |
          mkdir -p internal/gen
          cp -r tmp/openapi internal/gen/.
          cp -r tmp/api internal/gen/.

      - name: Install dependencies
        run: |
          go get EV3-API
          go install golang.org/x/tools/cmd/goimports@latest

      - name: Lint with goimports
        run: |
          goimports -l -w internal/gen/openapi
          gofmt -l -w internal/gen/openapi

      - name: Build package
        run: |
          go build -v -o server -ldflags="-s -w" EV3-API/cmd
        env:
          GOOS: linux
          GOARCH: arm
          GOARM: 5

      - name: Test
        run: |
          go test EV3-API/cmd -json > TestResults.json

      - name: Upload Go test results
        uses: actions/upload-artifact@v3
        with:
          name: Go-results
          path: TestResults.json

      - name: Upload Go binary
        uses: actions/upload-artifact@v3
        with:
          name: Go-binary
          path: server
          retention-days: 7

      - name: Gerate java client
        uses: docker://openapitools/openapi-generator-cli
        with:
          args: generate -i openapi/spec.yaml -o clients/java-tmp -g java -c openapi/java-client-config.yaml

      - name: Copy generated java code
        run: |
          mkdir -p clients/ev3-java/ev3api
          cp -r clients/java-tmp/* clients/ev3-java/ev3api/.

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Run build with Gradle Wrapper
        run: ./gradlew shadowJar
        working-directory: ./clients/ev3-java

      - name: Upload Java fat jar
        uses: actions/upload-artifact@v3
        with:
          name: Java-Jar
          path: clients/ev3-java/build/libs/ev3-java-1.0-SNAPSHOT-all.jar
          retention-days: 7
